server.port=8083
spring.application.name=reactive-mongo

#Alternate for the MongoConfig class:
spring.data.mongodb.uri=mongodb://localhost:27017/BeerWorks-WebFluxFn

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9000

