server.port=8083
spring.application.name=reactive-mongo

#Alternate for the MongoConfig class:
spring.data.mongodb.uri=mongodb://localhost:27017/BeerWorks-WebFluxFn

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9000

### For Spring Actuator integration with K8s
### http://localhost:8083/actuator/health/readiness and http://localhost:8083/actuator/health/liveness
management.endpoint.health.probes.enabled=true
management.health.readinessstate.enabled=true
management.health.livenessstate.enabled=true
